#!/bin/bash -e

source ../config
#source ./scripts/check_main_args

#if [ ! -z "$3" ]; then
#  export BOTNAME="$3"
#fi



#SERVER="testserver"
#SERVER="hakkinen"
SERVER="webber"


time ./run $SERVER.helloworldopen.com 8091 Nodraak ey8JSibC+rMZ0w




